#!/usr/bin/env python3
import sys
def first_number(n):
    for i in range(2,((n + 1)//2)+1):
        if (n%i == 0):
            return i
    return (n)

if (__name__=="__main__"):
    file_name = sys.argv[1]
    f = open(file_name,"r")
    i = 0
    k = 1
    A=[]
    A = list(f.readlines())
    for i in A:        
        p = first_number(int(i))
        q = int(i) // p
        if (k == len(A)):
            print(i,"=",q,"*",p)
        else:
            print(i[:-1],"=",q,"*",p)
        k = k + 1
    f.close()
