#!/usr/bin/env python3
import sys


def first_number(n):
    for i in range(2, ((n + 1)//2)+1):
        if (n % i == 0):
            return i
    return (n)


if (__name__ == "__main__"):
    file_name = sys.argv[1]
    f = open(file_name, "r")
    i = int(f.readline())
    p = first_number(int(i))
    q = int(i) // p
    print(str(i)+"="+str(q)+"*"+str(p))
    f.close()
